export const adminSidebarMenu = [
  {
    type: "link",
    label: "Dashboard",
    path: "/admin/food",
    icon: "LayoutDashboard",
    permissionKey: "dashboard",
  },
  {
    type: "link",
    label: "Point of Sale",
    path: "/admin/food/point-of-sale",
    icon: "CreditCard",
  },
  {
    type: "section",
    label: "FOOD MANAGEMENT",
    items: [
      {
        type: "link",
        label: "Food Approval",
        path: "/admin/food/food-approval",
        icon: "CheckCircle2",
        permissionKey: "foods",
      },
      {
        type: "expandable",
        label: "Foods",
        icon: "Utensils",
        permissionKey: "foods",
        subItems: [
          { label: "Restaurant Foods List", path: "/admin/food/foods", permissionKey: "foods" },
          { label: "Restaurant Addons List", path: "/admin/food/addons", permissionKey: "foods" },
        ],
      },
      {
        type: "expandable",
        label: "Categories",
        icon: "FolderTree",
        permissionKey: "categories",
        subItems: [{ label: "Category", path: "/admin/food/categories", permissionKey: "categories" }],
      },
      {
        type: "link",
        label: "Platform Fee",
        path: "/admin/food/fee-settings",
        icon: "IndianRupee",
        permissionKey: "settings",
      },
    ],
  },
  {
    type: "section",
    label: "RESTAURANT MANAGEMENT",
    items: [
      {
        type: "link",
        label: "Zone Setup",
        path: "/admin/food/zone-setup",
        icon: "MapPin",
        permissionKey: "zones",
      },
      {
        type: "expandable",
        label: "Restaurants",
        icon: "UtensilsCrossed",
        permissionKey: "restaurants",
        subItems: [
          { label: "Restaurants List", path: "/admin/food/restaurants", permissionKey: "restaurants" },
          { label: "New Joining Request", path: "/admin/food/restaurants/joining-request", permissionKey: "restaurants" },
          { label: "Restaurant Commission", path: "/admin/food/restaurants/commission", permissionKey: "transactions" },
          { label: "Restaurant Reviews", path: "/admin/food/restaurants/reviews", permissionKey: "restaurants" },
          { label: "Restaurant Complaints", path: "/admin/food/restaurants/complaints", permissionKey: "support" },
        ],
      },
    ],
  },
  {
    type: "section",
    label: "ORDER MANAGEMENT",
    items: [
      {
        type: "expandable",
        label: "Orders",
        icon: "FileText",
        permissionKey: "orders",
        subItems: [
          { label: "All", path: "/admin/food/orders/all", permissionKey: "orders" },
          { label: "Scheduled", path: "/admin/food/orders/scheduled", permissionKey: "orders" },
          { label: "Pending", path: "/admin/food/orders/pending", permissionKey: "orders" },
          { label: "Accepted", path: "/admin/food/orders/accepted", permissionKey: "orders" },
          { label: "Processing", path: "/admin/food/orders/processing", permissionKey: "orders" },
          { label: "Delivered", path: "/admin/food/orders/delivered", permissionKey: "orders" },
          { label: "Cancelled", path: "/admin/food/orders/canceled", permissionKey: "orders" },
          { label: "Restaurant cancelled", path: "/admin/food/orders/restaurant-cancelled", permissionKey: "orders" },
          { label: "Payment Failed", path: "/admin/food/orders/payment-failed", permissionKey: "orders" },
          { label: "Refunded", path: "/admin/food/orders/refunded", permissionKey: "orders" },
          { label: "Offline Payments", path: "/admin/food/orders/offline-payments", permissionKey: "orders" },
        ],
      },
    ],
  },
  {
    type: "section",
    label: "PROMOTIONS MANAGEMENT",
    items: [
      {
        type: "link",
        label: "Restaurant Coupons & Offers",
        path: "/admin/food/coupons",
        icon: "Gift",
        permissionKey: "promotions",
      },
      {
        type: "link",
        label: "Offer Approvals",
        path: "/admin/food/offer-approval",
        icon: "CheckCircle2",
        permissionKey: "promotions",
      },
      {
        type: "link",
        label: "Dining Offers",
        path: "/admin/food/dining-offers",
        icon: "Gift",
        permissionKey: "promotions",
      },
    ],
  },
  {
    type: "section",
    label: "REFERRAL & REWARDS",
    items: [
      { type: "link", label: "Referral Settings", path: "/admin/food/referral-settings", icon: "Gift", permissionKey: "settings" },
    ],
  },
  {
    type: "section",
    label: "CUSTOMER MANAGEMENT",
    items: [
      {
        type: "link",
        label: "Customers",
        path: "/admin/food/customers",
        icon: "Users",
        permissionKey: "customers",
      },
      {
        type: "link",
        label: "Support Tickets (User & Restaurant)",
        path: "/admin/food/support-tickets",
        icon: "MessageSquare",
        permissionKey: "support",
      },
    ],
  },
  {
    type: "section",
    label: "HELP & SUPPORT",
    items: [
      { type: "link", label: "User Feedback", path: "/admin/food/contact-messages", icon: "Mail", permissionKey: "support" },
      { type: "link", label: "Safety Emergency Reports", path: "/admin/food/safety-emergency-reports", icon: "AlertTriangle", permissionKey: "support" },
    ],
  },
  {
    type: "section",
    label: "REPORT MANAGEMENT",
    items: [
      { type: "link", label: "Transaction Report", path: "/admin/food/transaction-report", icon: "FileText", permissionKey: "reports" },
      { type: "link", label: "Order Report", path: "/admin/food/order-report/regular", icon: "FileText", permissionKey: "reports" },
      { type: "link", label: "Dining Order Report", path: "/admin/food/dining-order-report", icon: "FileText", permissionKey: "reports" },
      { type: "link", label: "Dining Transaction Report", path: "/admin/food/dining-transaction-report", icon: "FileText", permissionKey: "reports" },
      { type: "link", label: "Tax Report", path: "/admin/food/tax-report", icon: "Receipt", permissionKey: "reports" },
      {
        type: "expandable",
        label: "Restaurant Report",
        icon: "FileText",
        permissionKey: "reports",
        subItems: [{ label: "Restaurant Report", path: "/admin/food/restaurant-report", permissionKey: "reports" }],
      },
      {
        type: "expandable",
        label: "Customer Report",
        icon: "FileText",
        permissionKey: "reports",
        subItems: [{ label: "Feedback Experience", path: "/admin/food/customer-report/feedback-experience", permissionKey: "reports" }],
      },
    ],
  },
  {
    type: "section",
    label: "TRANSACTION MANAGEMENT",
    items: [
      { type: "link", label: "Restaurant Withdraws", path: "/admin/food/restaurant-withdraws", icon: "CreditCard", permissionKey: "transactions" },
    ],
  },
  {
    type: "section",
    label: "BANNER SETTINGS",
    items: [
      { type: "link", label: "Landing Page Management", path: "/admin/food/hero-banner-management", icon: "Image", permissionKey: "settings" },
    ],
  },
  {
    type: "section",
    label: "DINING MANAGEMENT",
    items: [
      { type: "link", label: "Dining Banners", path: "/admin/food/dining-management", icon: "UtensilsCrossed", permissionKey: "dining" },
      { type: "link", label: "Dining List", path: "/admin/food/dining-list", icon: "FileText", permissionKey: "dining" },
      { type: "link", label: "Dining Orders", path: "/admin/food/dining-orders", icon: "ClipboardList", permissionKey: "dining" },
      { type: "link", label: "Dining Bookings", path: "/admin/food/dining-bookings", icon: "Calendar", permissionKey: "dining" },
      { type: "link", label: "Dining Sessions", path: "/admin/food/dining-sessions", icon: "Users", permissionKey: "dining" },
      { type: "link", label: "Dining Finance", path: "/admin/food/dining-finance", icon: "Wallet", permissionKey: "dining" },
      { type: "link", label: "Dining Commission", path: "/admin/food/dining/restaurants/commission", icon: "Percent", permissionKey: "dining" },
      { type: "link", label: "Dining Fee Settings", path: "/admin/food/dining/fee-settings", icon: "IndianRupee", permissionKey: "dining" },
    ],
  },
  {
    type: "section",
    label: "SYSTEM SETTINGS",
    items: [
      { type: "link", label: "Broadcast Notification", path: "/admin/food/broadcast-notification", icon: "Bell", permissionKey: "settings" },
      { type: "link", label: "Business Setup", path: "/admin/food/business-setup", icon: "Settings", permissionKey: "settings" },
      { type: "link", label: "Refund Settings", path: "/admin/food/settings/refund-policy", icon: "Receipt", permissionKey: "settings" },
      { type: "link", label: "Manage Admins", path: "/admin/food/manage-admins", icon: "UserCog", permissionKey: "superadmin" },
    ],
  },
  {
    type: "section",
    label: "PAGES & SOCIAL MEDIA",
    items: [
      { type: "link", label: "About Us", path: "/admin/food/pages-social-media/about", icon: "Globe", permissionKey: "pages" },
      { type: "link", label: "Terms & Conditions", path: "/admin/food/pages-social-media/terms", icon: "FileText", permissionKey: "pages" },
      { type: "link", label: "Privacy Policy", path: "/admin/food/pages-social-media/privacy", icon: "Lock", permissionKey: "pages" },
      { type: "link", label: "Restaurant Terms", path: "/admin/food/pages-social-media/restaurant-terms", icon: "FileText", permissionKey: "pages" },
      { type: "link", label: "Restaurant Privacy", path: "/admin/food/pages-social-media/restaurant-privacy", icon: "Lock", permissionKey: "pages" },
      { type: "link", label: "Refund Policy", path: "/admin/food/pages-social-media/refund", icon: "Receipt", permissionKey: "pages" },
      { type: "link", label: "Shipping Policy", path: "/admin/food/pages-social-media/shipping", icon: "Truck", permissionKey: "pages" },
      { type: "link", label: "Cancellation Policy", path: "/admin/food/pages-social-media/cancellation", icon: "X", permissionKey: "pages" },
    ],
  },
];
